.Dd $Mdocdate: August 08 2018$
.Dt PLOOT-FEED 1
.Os
.
.
.Sh NAME
.
.Nm ploot-feed
.Nd plot a continuous stream of data from standard input.
.
.
.Sh SYNOPSIS
.
.Nm ploot-feed
.Op Fl w Ar width
.Ar maxval...
.
.
.Sh DESCRIPTION
.
The
.Nm
utility plots a text chart of csv values coming from stdin in real time.
.
.Bl -tag -width 6n
.
.It Ar width
is the width of the plot in characters.
.
.It Ar maxval
is a list of argument that specify the maximum value for each column.
If the input csv have 5 columns in addition of the timestamp, there must
be 5 maxval arguments.
.
.El
.
.Pp
The input format is documented in the
.Xr ploot-csv 7
manual page.
.
.
.Sh EXIT STATUS
.Ex -std
.
.
.Sh EXAMPLES
.
.Bd -literal -offset indent
$ cat <<EOF >sample.txt
epoch,free_memory,process_count
1533752053,16.3,45
1533752054,18.7,42
1533752055,40.1,39
1533752056,40.1,39
EOF
$ ploot-feed -w 80 1 1 <sample.txt
.Ed
.
.
.Sh SEE ALSO
.
.Xr ploot-ff 1 ,
.Xr ploot-format 7
.
.
.Sh HISTORY
.
.Nm
earned its author a bitreich.org medal of misspelled program name.
.
.Pp
.Nm
was written at
.Lk gopher://bitreich.org/1/scm/ploot/ "Bitreich"
.
.
.Sh AUTHORS
.
.An Josuah Demangeon
.Aq Mt mail@josuah.net
.
.
.Sh BUGS
.
.Nm
does not make any math on the input: if the timestamps are not at regular
interval, ploot will still print one output line every 4 lines read,
regardless of the time interval.
.
.Pp
However, the timestamp printed on the left is always exact.
