.Dd $Mdocdate: February 01 2020$
.Dt PLOOT-CSV 7
.Os
.
.
.Sh NAME
.
.Nm ploot-csv
.Nd input format used by the ploot set of programs
.
.
.Sh SYNOPSIS
.
.Bd -literal
epoch,column-name-1,column-name-2
timestamp,value1,value2
timestamp,value1,value2
…
.Ed
.
.
.Sh DESCRIPTION
.
This is the simple comma-separated format used by the ploot-* programs.
.
.
.Sh INPUT FORMAT
.
.Nm
has a first header line, then zero or more data lines, both
comma-separated list of values.
.
.
.Ss Header line
.
The input must contain a first header line with the label of each column in order.
The first column is always
.Dq epoch .
Then there are the actual column names.
.
.Bd -literal -offset indent
epoch,free_memory,process_count
.Ed
.
.
.Ss Data lines
.
The following lines are the data.
The first column is always an unix timestamp as in
.Vt time_t .
The remaining columns are values parsed as floating point numbers by
.Xr strtod 3 :
.
.Bd -literal -offset indent
1533752053,16.3,45
1533752054,18.7,42
1533752055,40.1,39
1533752056,40.1,39
.Ed
.
.
.Sh SEE ALSO
.
.Xr ploot-feed 1 ,
.Xr ploot-ff 1
.
.Sh HISTORY
.
.Nm
was defined at
.Lk gopher://bitreich.org/1/scm/ploot/ "Bitreich"
.
.
.Sh AUTHORS
.
.An Josuah Demangeon
.Aq Mt me@josuah.net
